### ISSUE TITLE
Replace `purrr::cross2()` for creating GRIM rasters

### ISSUE THREAD

**Issue by lhdjung** [lhdjung/scrutiny#53]
Although deprecated, [`purrr::cross2()`](https://purrr.tidyverse.org/reference/cross.html) is still used in [data-gen.R](https://github.com/lhdjung/scrutiny/blob/main/data-raw/data-gen.R) to create combinations of GRIM-inconsistent values given some number of decimal places (either 1 or 2) and a rounding method. The resulting vectors are used to create the background rasters in `grim_plot()`.

Deprecated functions are going to be removed at some point, so this solution is not going to work forever. What to do if I want to generate GRIM rasters in a future where `cross2()` is no longer part of purrr?

The officially recommended replacement for `cross2()` is [`tidyr::expand_grid()`](https://tidyr.tidyverse.org/reference/expand_grid.html), but this function imposes a specific order on the output values, which would not create the desired raster patterns. `base::expand.grid()` does not order the results but works similarly otherwise:

``` r
tidyr::expand_grid(x = 1:3, y = 1:2)
#> # A tibble: 6 × 2
#>       x     y
#>   <int> <int>
#> 1     1     1
#> 2     1     2
#> 3     2     1
#> 4     2     2
#> 5     3     1
#> 6     3     2

expand.grid(x = 1:3, y = 1:2) |> tibble::as_tibble()
#> # A tibble: 6 × 2
#>       x     y
#>   <int> <int>
#> 1     1     1
#> 2     2     1
#> 3     3     1
#> 4     1     2
#> 5     2     2
#> 6     3     2
```

<sup>Created on 2024-02-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If this doesn't fit my use case, I might need to temporarily reinstall a version of purrr that still features `cross2()`, such as 1.0.2, if I want to generate the rasters in the future.

**Comment by lhdjung** [comment]
Raster generation will likely keep relying on `cross2()` in the future, even if it means temporarily reinstalling an earlier version of purrr.

**Comment by olivroy** [comment]
Since it is [soft-deprecated](https://lifecycle.r-lib.org/articles/stages.html#deprecated), it should stay around for a little bit. If you look at the source code of `cross2(.x, .y, .filter)`, you may want to replace those calls with `purrr::cross(list(.x, .y), .filter = .filter)`, which is also soft-deprecated, but it may avoid 2 deprecation warnings.

Another solution if you are under MIT license is to inline some of the code in your package directly, by adding the correct licenses. This would make your code more future proof to hard deprecations.

However, the solution I would use would be to create a wrapper around `expand.grid()`, and adjust the output how you want it to be. This would be more light weight and resilient to any future change.

```r
my_cross2 <- function(x, y, filter) {
  out <- expand.grid(x, y)
  # further manipulations on res to get it in the shape you need.
  
  res
}
```

**Comment by olivroy** [comment]
Oh I read too fast. You're right. I was under the impression this was under `R/`. Please disregard what I just said :)

**Comment by lhdjung** [comment]
No problem, I'm always happy about your contributions!
