### ISSUE TITLE
Simplify DEBIT so that it only spends time on TRUE/FALSE

### ISSUE THREAD

**Issue by LukasWallrich** [lhdjung/scrutiny#61]
For mapping, speed matters - so DEBIT should be quick - would seem to literally require running this line?

SD == sqrt(M * (1 - M) / N)

**Comment by lhdjung** [comment]
It is true that mapping can be a performance bottleneck. However, DEBIT also needs to take rounding into account (see the [preprint,](https://osf.io/5vb3u) p. 6). Consider that `unround()` was originally written as a helper for DEBIT. Hence there are some complexities that are not captured by a simple formula.

DEBIT is an extremely narrow tool, so it's unlikely to be used a great deal, and each usage will be a one-off analysis. That's why I think it's not performance-critical.

These benchmarks seem acceptable (and were better at other times I've measured), even when systematically varying the reported values using `debit_map_seq()`:

``` r
library(scrutiny)
#> Warning: package 'scrutiny' was built under R version 4.3.2
bench::mark(
    debit_map(pigs3),
    debit_map_seq(pigs3),
    iterations = 500,
    check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>           <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 debit_map(pigs3)       54.6ms    139ms      7.97    8.72MB     6.63
#> 2 debit_map_seq(pigs3)  328.1ms    843ms      1.13    4.54MB     5.33
```

<sup>Created on 2024-03-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Also, your formula is different from those in the preprint (pp. 4f.) and returns different results, but I haven't spent much thought on this.

**Comment by LukasWallrich** [comment]
Don't worry about it - you are right that rounding makes this a little
harder and this will very rarely be used on large datasets ...

**Comment by LukasWallrich** [comment]
You are right - optimising this is not a priority. 

The formula difference is just whether N is used directly (as the population SD) or as N/N-1 as the sample SD. The sample SD as per the preprint is certainly more common - but not used exclusively - so that might be worth documenting as a possible reason for discrepancies?
